name: Test Runner

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  runAllTests:
    name: ${{ matrix.unityVersion }} ${{ matrix.testMode }} tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - editmode
        unityVersion:
          - 2021.3.7f1
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "rYuuk/PackageSubmoduleInUnityProject"
          submodules: true
          token: ${{ secrets.PAT }}
      - name: Checkout submodule branch
        run: |
          pwd
          cd Assets/TestPackage
          pwd
          git status
          git fetch
          git checkout origin/${{ github.event.pull_request.head.ref }}
          git pull origin ${{ github.event.pull_request.head.ref }}
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-
          restore-keys: |
            Library-
      - name: Tests 🛠️
        id: tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          projectPath: ${{ matrix.projectPath }}
          checkName: ${{ matrix.unityVersion }} ${{ matrix.testMode }} tests result
          githubToken: ${{ secrets.GITHUB_TOKEN }}
